id: PBEA4D81E
initial_creation_type: input
source_metadata:
  title: Chöying Tobden Dorje
  language: en
  description: 'Texts by and about Chöying Tobden Dorje (chos dbyings stobs ldan rdo
    rje, 1785–1848):'
  volume:
    3b6d49dcb2df410e827a446fcd11120d:
      title: A Concise Supplication to the Most Noble Tārā
      parent: Prayers
created_at: '2022-02-28T22:49:08.127003'
last_modified_at: '2022-02-28T22:49:08.127008'
